
[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/opt/homebrew/lib/node_modules/@vue/language-server"
languages = ["vue"]

# [language-server.vuels.config.typescript]
# tsdk = '/opt/homebrew/lib/node_modules/typescript/lib'

[[language]]
name = "vue"
auto-format = true
language-servers = [ "vuels", "typescript-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

